/**
 * A curated Unicode emoji dataset for the composer picker. Deliberately not exhaustive — a
 * common, reviewable subset (no dependency, small bundle). Emoji are literal characters, so they
 * need no special render path: they flow straight through the message content as text.
 *
 * Each emoji carries search keywords beyond its name so e.g. "lol" finds 😂. `searchEmojis` is a
 * pure flat-filter over name + keywords (used when the search box is non-empty).
 */
export interface EmojiItem {
  char: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  name: string;
  /** Font Awesome icon for the category tab. */
  icon: string;
  emojis: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & People',
    icon: 'fa-face-smile',
    emojis: [
      { char: '😀', name: 'grinning face', keywords: ['smile', 'happy', 'grin'] },
      { char: '😃', name: 'grinning face with big eyes', keywords: ['smile', 'happy'] },
      { char: '😄', name: 'grinning face with smiling eyes', keywords: ['smile', 'happy', 'laugh'] },
      { char: '😁', name: 'beaming face with smiling eyes', keywords: ['smile', 'grin'] },
      { char: '😆', name: 'grinning squinting face', keywords: ['laugh', 'haha', 'lol'] },
      { char: '😅', name: 'grinning face with sweat', keywords: ['laugh', 'sweat', 'relief'] },
      { char: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'laugh', 'lol', 'haha'] },
      { char: '😂', name: 'face with tears of joy', keywords: ['laugh', 'lol', 'haha', 'cry', 'joy'] },
      { char: '🙂', name: 'slightly smiling face', keywords: ['smile'] },
      { char: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm'] },
      { char: '😉', name: 'winking face', keywords: ['wink', 'flirt'] },
      { char: '😊', name: 'smiling face with smiling eyes', keywords: ['blush', 'happy', 'smile'] },
      { char: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent'] },
      { char: '🥰', name: 'smiling face with hearts', keywords: ['love', 'adore', 'crush'] },
      { char: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'crush', 'heart'] },
      { char: '🤩', name: 'star-struck', keywords: ['star', 'eyes', 'wow', 'amazing'] },
      { char: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love', 'flirt'] },
      { char: '😗', name: 'kissing face', keywords: ['kiss'] },
      { char: '😚', name: 'kissing face with closed eyes', keywords: ['kiss'] },
      { char: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss'] },
      { char: '😋', name: 'face savoring food', keywords: ['yum', 'tasty', 'tongue'] },
      { char: '😛', name: 'face with tongue', keywords: ['tongue', 'silly'] },
      { char: '😜', name: 'winking face with tongue', keywords: ['tongue', 'wink', 'silly'] },
      { char: '🤪', name: 'zany face', keywords: ['crazy', 'silly', 'goofy'] },
      { char: '😝', name: 'squinting face with tongue', keywords: ['tongue', 'silly'] },
      { char: '🤑', name: 'money-mouth face', keywords: ['money', 'rich', 'dollar'] },
      { char: '🤗', name: 'hugging face', keywords: ['hug', 'embrace'] },
      { char: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'giggle'] },
      { char: '🤫', name: 'shushing face', keywords: ['quiet', 'shh', 'secret'] },
      { char: '🤔', name: 'thinking face', keywords: ['think', 'hmm', 'consider'] },
      { char: '🤐', name: 'zipper-mouth face', keywords: ['quiet', 'secret'] },
      { char: '🤨', name: 'face with raised eyebrow', keywords: ['skeptical', 'suspicious'] },
      { char: '😐', name: 'neutral face', keywords: ['meh', 'blank'] },
      { char: '😑', name: 'expressionless face', keywords: ['blank', 'meh'] },
      { char: '😶', name: 'face without mouth', keywords: ['silent', 'speechless'] },
      { char: '😏', name: 'smirking face', keywords: ['smirk', 'smug'] },
      { char: '😒', name: 'unamused face', keywords: ['meh', 'annoyed', 'unimpressed'] },
      { char: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll', 'annoyed'] },
      { char: '😬', name: 'grimacing face', keywords: ['awkward', 'cringe'] },
      { char: '🤥', name: 'lying face', keywords: ['liar', 'pinocchio'] },
      { char: '😌', name: 'relieved face', keywords: ['relief', 'calm', 'content'] },
      { char: '😔', name: 'pensive face', keywords: ['sad', 'thoughtful'] },
      { char: '😪', name: 'sleepy face', keywords: ['tired', 'sleep'] },
      { char: '🤤', name: 'drooling face', keywords: ['drool', 'hungry'] },
      { char: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz', 'tired'] },
      { char: '😷', name: 'face with medical mask', keywords: ['sick', 'mask', 'ill'] },
      { char: '🤒', name: 'face with thermometer', keywords: ['sick', 'ill', 'fever'] },
      { char: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injured'] },
      { char: '🤢', name: 'nauseated face', keywords: ['sick', 'gross', 'disgust'] },
      { char: '🤮', name: 'face vomiting', keywords: ['sick', 'vomit', 'gross'] },
      { char: '🤧', name: 'sneezing face', keywords: ['sneeze', 'sick'] },
      { char: '🥵', name: 'hot face', keywords: ['hot', 'sweat', 'heat'] },
      { char: '🥶', name: 'cold face', keywords: ['cold', 'freezing'] },
      { char: '😵', name: 'dizzy face', keywords: ['dizzy', 'confused'] },
      { char: '🤯', name: 'exploding head', keywords: ['mind', 'blown', 'shocked'] },
      { char: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'yeehaw'] },
      { char: '🥳', name: 'partying face', keywords: ['party', 'celebrate', 'birthday'] },
      { char: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'sunglasses'] },
      { char: '🤓', name: 'nerd face', keywords: ['nerd', 'geek', 'smart'] },
      { char: '🧐', name: 'face with monocle', keywords: ['inspect', 'fancy'] },
      { char: '😕', name: 'confused face', keywords: ['confused', 'unsure'] },
      { char: '😟', name: 'worried face', keywords: ['worried', 'concern'] },
      { char: '🙁', name: 'slightly frowning face', keywords: ['sad', 'frown'] },
      { char: '😮', name: 'face with open mouth', keywords: ['wow', 'surprised'] },
      { char: '😯', name: 'hushed face', keywords: ['surprised', 'wow'] },
      { char: '😲', name: 'astonished face', keywords: ['shocked', 'wow'] },
      { char: '😳', name: 'flushed face', keywords: ['embarrassed', 'blush'] },
      { char: '🥺', name: 'pleading face', keywords: ['please', 'puppy', 'beg'] },
      { char: '😦', name: 'frowning face with open mouth', keywords: ['sad', 'frown'] },
      { char: '😧', name: 'anguished face', keywords: ['anguish', 'shocked'] },
      { char: '😨', name: 'fearful face', keywords: ['scared', 'fear'] },
      { char: '😰', name: 'anxious face with sweat', keywords: ['anxious', 'nervous'] },
      { char: '😥', name: 'sad but relieved face', keywords: ['sad', 'relief'] },
      { char: '😢', name: 'crying face', keywords: ['cry', 'sad', 'tear'] },
      { char: '😭', name: 'loudly crying face', keywords: ['cry', 'sob', 'sad'] },
      { char: '😱', name: 'face screaming in fear', keywords: ['scream', 'scared', 'shocked'] },
      { char: '😖', name: 'confounded face', keywords: ['frustrated', 'confused'] },
      { char: '😣', name: 'persevering face', keywords: ['struggle', 'persevere'] },
      { char: '😞', name: 'disappointed face', keywords: ['sad', 'disappointed'] },
      { char: '😓', name: 'downcast face with sweat', keywords: ['sad', 'sweat'] },
      { char: '😩', name: 'weary face', keywords: ['tired', 'frustrated'] },
      { char: '😫', name: 'tired face', keywords: ['tired', 'exhausted'] },
      { char: '🥱', name: 'yawning face', keywords: ['yawn', 'bored', 'tired'] },
      { char: '😤', name: 'face with steam from nose', keywords: ['frustrated', 'triumph'] },
      { char: '😡', name: 'pouting face', keywords: ['angry', 'mad', 'rage'] },
      { char: '😠', name: 'angry face', keywords: ['angry', 'mad'] },
      { char: '🤬', name: 'face with symbols on mouth', keywords: ['swear', 'curse', 'angry'] },
      { char: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil', 'mischief'] },
      { char: '👿', name: 'angry face with horns', keywords: ['devil', 'angry'] },
      { char: '💀', name: 'skull', keywords: ['dead', 'death', 'skull'] },
      { char: '💩', name: 'pile of poo', keywords: ['poop', 'poo', 'crap'] },
      { char: '🤡', name: 'clown face', keywords: ['clown', 'silly'] },
      { char: '👻', name: 'ghost', keywords: ['ghost', 'boo', 'halloween'] },
      { char: '👽', name: 'alien', keywords: ['alien', 'ufo', 'space'] },
      { char: '🤖', name: 'robot', keywords: ['robot', 'bot'] },
      { char: '😺', name: 'grinning cat', keywords: ['cat', 'smile'] },
      { char: '😸', name: 'grinning cat with smiling eyes', keywords: ['cat', 'smile'] },
      { char: '😹', name: 'cat with tears of joy', keywords: ['cat', 'laugh'] },
      { char: '😻', name: 'smiling cat with heart-eyes', keywords: ['cat', 'love'] },
      { char: '🙀', name: 'weary cat', keywords: ['cat', 'shocked'] },
      { char: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'bye', 'hi'] },
      { char: '🤚', name: 'raised back of hand', keywords: ['hand', 'stop'] },
      { char: '✋', name: 'raised hand', keywords: ['hand', 'stop', 'high five'] },
      { char: '🖖', name: 'vulcan salute', keywords: ['spock', 'star trek'] },
      { char: '👌', name: 'OK hand', keywords: ['ok', 'perfect', 'okay'] },
      { char: '🤏', name: 'pinching hand', keywords: ['small', 'tiny'] },
      { char: '✌️', name: 'victory hand', keywords: ['peace', 'victory'] },
      { char: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope'] },
      { char: '🤟', name: 'love-you gesture', keywords: ['love', 'rock'] },
      { char: '🤘', name: 'sign of the horns', keywords: ['rock', 'metal'] },
      { char: '🤙', name: 'call me hand', keywords: ['call', 'shaka', 'hang loose'] },
      { char: '👈', name: 'backhand index pointing left', keywords: ['point', 'left'] },
      { char: '👉', name: 'backhand index pointing right', keywords: ['point', 'right'] },
      { char: '👆', name: 'backhand index pointing up', keywords: ['point', 'up'] },
      { char: '👇', name: 'backhand index pointing down', keywords: ['point', 'down'] },
      { char: '☝️', name: 'index pointing up', keywords: ['point', 'up', 'one'] },
      { char: '👍', name: 'thumbs up', keywords: ['like', 'yes', 'good', 'approve'] },
      { char: '👎', name: 'thumbs down', keywords: ['dislike', 'no', 'bad'] },
      { char: '✊', name: 'raised fist', keywords: ['fist', 'power'] },
      { char: '👊', name: 'oncoming fist', keywords: ['fist', 'punch', 'bump'] },
      { char: '🤛', name: 'left-facing fist', keywords: ['fist', 'bump'] },
      { char: '🤜', name: 'right-facing fist', keywords: ['fist', 'bump'] },
      { char: '👏', name: 'clapping hands', keywords: ['clap', 'applause', 'bravo'] },
      { char: '🙌', name: 'raising hands', keywords: ['celebrate', 'praise', 'hooray'] },
      { char: '👐', name: 'open hands', keywords: ['hands', 'open'] },
      { char: '🤲', name: 'palms up together', keywords: ['pray', 'cup'] },
      { char: '🤝', name: 'handshake', keywords: ['deal', 'agree', 'shake'] },
      { char: '🙏', name: 'folded hands', keywords: ['pray', 'please', 'thanks', 'hope'] },
      { char: '✍️', name: 'writing hand', keywords: ['write', 'pen'] },
      { char: '💅', name: 'nail polish', keywords: ['nails', 'fancy', 'sassy'] },
      { char: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle', 'flex'] },
      { char: '🧠', name: 'brain', keywords: ['smart', 'brain', 'think'] },
      { char: '👀', name: 'eyes', keywords: ['look', 'see', 'watch'] },
      { char: '👶', name: 'baby', keywords: ['baby', 'infant'] },
      { char: '🧒', name: 'child', keywords: ['kid', 'child'] },
      { char: '👦', name: 'boy', keywords: ['boy', 'kid'] },
      { char: '👧', name: 'girl', keywords: ['girl', 'kid'] },
      { char: '🧑', name: 'person', keywords: ['person', 'adult'] },
      { char: '👨', name: 'man', keywords: ['man', 'male'] },
      { char: '👩', name: 'woman', keywords: ['woman', 'female'] },
      { char: '🧓', name: 'older person', keywords: ['old', 'elder'] },
      { char: '👴', name: 'old man', keywords: ['old', 'grandpa'] },
      { char: '👵', name: 'old woman', keywords: ['old', 'grandma'] },
      { char: '🤴', name: 'prince', keywords: ['prince', 'royal'] },
      { char: '👸', name: 'princess', keywords: ['princess', 'royal'] },
      { char: '🦸', name: 'superhero', keywords: ['hero', 'super'] },
      { char: '🦹', name: 'supervillain', keywords: ['villain', 'evil'] },
      { char: '🎅', name: 'Santa Claus', keywords: ['santa', 'christmas'] },
      { char: '🤰', name: 'pregnant woman', keywords: ['pregnant', 'baby'] },
      { char: '💃', name: 'woman dancing', keywords: ['dance', 'party'] },
      { char: '🕺', name: 'man dancing', keywords: ['dance', 'party'] },
    ],
  },
  {
    id: 'nature',
    name: 'Animals & Nature',
    icon: 'fa-paw',
    emojis: [
      { char: '🐶', name: 'dog face', keywords: ['dog', 'puppy', 'pet'] },
      { char: '🐱', name: 'cat face', keywords: ['cat', 'kitten', 'pet'] },
      { char: '🐭', name: 'mouse face', keywords: ['mouse'] },
      { char: '🐹', name: 'hamster', keywords: ['hamster', 'pet'] },
      { char: '🐰', name: 'rabbit face', keywords: ['rabbit', 'bunny'] },
      { char: '🦊', name: 'fox', keywords: ['fox'] },
      { char: '🐻', name: 'bear', keywords: ['bear'] },
      { char: '🐼', name: 'panda', keywords: ['panda'] },
      { char: '🐨', name: 'koala', keywords: ['koala'] },
      { char: '🐯', name: 'tiger face', keywords: ['tiger'] },
      { char: '🦁', name: 'lion', keywords: ['lion'] },
      { char: '🐮', name: 'cow face', keywords: ['cow'] },
      { char: '🐷', name: 'pig face', keywords: ['pig'] },
      { char: '🐸', name: 'frog', keywords: ['frog'] },
      { char: '🐵', name: 'monkey face', keywords: ['monkey'] },
      { char: '🙈', name: 'see-no-evil monkey', keywords: ['monkey', 'shy'] },
      { char: '🐔', name: 'chicken', keywords: ['chicken'] },
      { char: '🐧', name: 'penguin', keywords: ['penguin'] },
      { char: '🐦', name: 'bird', keywords: ['bird'] },
      { char: '🐤', name: 'baby chick', keywords: ['chick', 'bird'] },
      { char: '🦆', name: 'duck', keywords: ['duck'] },
      { char: '🦅', name: 'eagle', keywords: ['eagle', 'bird'] },
      { char: '🦉', name: 'owl', keywords: ['owl', 'bird'] },
      { char: '🦇', name: 'bat', keywords: ['bat'] },
      { char: '🐺', name: 'wolf', keywords: ['wolf'] },
      { char: '🐗', name: 'boar', keywords: ['boar', 'pig'] },
      { char: '🐴', name: 'horse face', keywords: ['horse'] },
      { char: '🦄', name: 'unicorn', keywords: ['unicorn', 'magic'] },
      { char: '🐝', name: 'honeybee', keywords: ['bee'] },
      { char: '🐛', name: 'bug', keywords: ['bug', 'insect'] },
      { char: '🦋', name: 'butterfly', keywords: ['butterfly'] },
      { char: '🐌', name: 'snail', keywords: ['snail', 'slow'] },
      { char: '🐞', name: 'lady beetle', keywords: ['ladybug', 'bug'] },
      { char: '🐜', name: 'ant', keywords: ['ant', 'bug'] },
      { char: '🕷️', name: 'spider', keywords: ['spider'] },
      { char: '🦂', name: 'scorpion', keywords: ['scorpion'] },
      { char: '🐢', name: 'turtle', keywords: ['turtle', 'slow'] },
      { char: '🐍', name: 'snake', keywords: ['snake'] },
      { char: '🦎', name: 'lizard', keywords: ['lizard'] },
      { char: '🐙', name: 'octopus', keywords: ['octopus'] },
      { char: '🦑', name: 'squid', keywords: ['squid'] },
      { char: '🦐', name: 'shrimp', keywords: ['shrimp'] },
      { char: '🦀', name: 'crab', keywords: ['crab'] },
      { char: '🐠', name: 'tropical fish', keywords: ['fish'] },
      { char: '🐟', name: 'fish', keywords: ['fish'] },
      { char: '🐬', name: 'dolphin', keywords: ['dolphin'] },
      { char: '🐳', name: 'spouting whale', keywords: ['whale'] },
      { char: '🦈', name: 'shark', keywords: ['shark'] },
      { char: '🐊', name: 'crocodile', keywords: ['crocodile', 'alligator'] },
      { char: '🐘', name: 'elephant', keywords: ['elephant'] },
      { char: '🦏', name: 'rhinoceros', keywords: ['rhino'] },
      { char: '🦒', name: 'giraffe', keywords: ['giraffe'] },
      { char: '🐪', name: 'camel', keywords: ['camel'] },
      { char: '🐎', name: 'horse', keywords: ['horse', 'race'] },
      { char: '🐖', name: 'pig', keywords: ['pig'] },
      { char: '🐑', name: 'ewe', keywords: ['sheep'] },
      { char: '🐐', name: 'goat', keywords: ['goat'] },
      { char: '🦌', name: 'deer', keywords: ['deer'] },
      { char: '🐕', name: 'dog', keywords: ['dog'] },
      { char: '🐈', name: 'cat', keywords: ['cat'] },
      { char: '🌸', name: 'cherry blossom', keywords: ['flower', 'spring'] },
      { char: '🌹', name: 'rose', keywords: ['flower', 'rose', 'love'] },
      { char: '🌺', name: 'hibiscus', keywords: ['flower'] },
      { char: '🌻', name: 'sunflower', keywords: ['flower', 'sun'] },
      { char: '🌷', name: 'tulip', keywords: ['flower', 'tulip'] },
      { char: '🌼', name: 'blossom', keywords: ['flower'] },
      { char: '🌱', name: 'seedling', keywords: ['plant', 'sprout', 'grow'] },
      { char: '🌲', name: 'evergreen tree', keywords: ['tree'] },
      { char: '🌳', name: 'deciduous tree', keywords: ['tree'] },
      { char: '🌴', name: 'palm tree', keywords: ['tree', 'beach'] },
      { char: '🌵', name: 'cactus', keywords: ['cactus', 'desert'] },
      { char: '🍀', name: 'four leaf clover', keywords: ['luck', 'clover'] },
      { char: '🍁', name: 'maple leaf', keywords: ['leaf', 'autumn', 'fall'] },
      { char: '🍂', name: 'fallen leaf', keywords: ['leaf', 'autumn'] },
      { char: '🌿', name: 'herb', keywords: ['plant', 'leaf'] },
      { char: '☀️', name: 'sun', keywords: ['sun', 'sunny', 'weather'] },
      { char: '🌙', name: 'crescent moon', keywords: ['moon', 'night'] },
      { char: '⭐', name: 'star', keywords: ['star'] },
      { char: '🌟', name: 'glowing star', keywords: ['star', 'sparkle'] },
      { char: '✨', name: 'sparkles', keywords: ['sparkle', 'shiny', 'magic'] },
      { char: '⚡', name: 'high voltage', keywords: ['lightning', 'bolt', 'electric'] },
      { char: '🔥', name: 'fire', keywords: ['fire', 'lit', 'hot', 'flame'] },
      { char: '🌈', name: 'rainbow', keywords: ['rainbow', 'pride'] },
      { char: '☁️', name: 'cloud', keywords: ['cloud', 'weather'] },
      { char: '🌧️', name: 'cloud with rain', keywords: ['rain', 'weather'] },
      { char: '⛄', name: 'snowman', keywords: ['snow', 'winter'] },
      { char: '❄️', name: 'snowflake', keywords: ['snow', 'cold', 'winter'] },
      { char: '💧', name: 'droplet', keywords: ['water', 'drop'] },
      { char: '🌊', name: 'water wave', keywords: ['wave', 'ocean', 'sea'] },
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: 'fa-mug-hot',
    emojis: [
      { char: '🍏', name: 'green apple', keywords: ['apple', 'fruit'] },
      { char: '🍎', name: 'red apple', keywords: ['apple', 'fruit'] },
      { char: '🍐', name: 'pear', keywords: ['fruit'] },
      { char: '🍊', name: 'tangerine', keywords: ['orange', 'fruit'] },
      { char: '🍋', name: 'lemon', keywords: ['lemon', 'fruit', 'sour'] },
      { char: '🍌', name: 'banana', keywords: ['banana', 'fruit'] },
      { char: '🍉', name: 'watermelon', keywords: ['watermelon', 'fruit'] },
      { char: '🍇', name: 'grapes', keywords: ['grapes', 'fruit'] },
      { char: '🍓', name: 'strawberry', keywords: ['strawberry', 'fruit'] },
      { char: '🫐', name: 'blueberries', keywords: ['blueberry', 'fruit'] },
      { char: '🍒', name: 'cherries', keywords: ['cherry', 'fruit'] },
      { char: '🍑', name: 'peach', keywords: ['peach', 'fruit'] },
      { char: '🥭', name: 'mango', keywords: ['mango', 'fruit'] },
      { char: '🍍', name: 'pineapple', keywords: ['pineapple', 'fruit'] },
      { char: '🥥', name: 'coconut', keywords: ['coconut'] },
      { char: '🥝', name: 'kiwi fruit', keywords: ['kiwi', 'fruit'] },
      { char: '🍅', name: 'tomato', keywords: ['tomato', 'vegetable'] },
      { char: '🥑', name: 'avocado', keywords: ['avocado'] },
      { char: '🥦', name: 'broccoli', keywords: ['broccoli', 'vegetable'] },
      { char: '🥕', name: 'carrot', keywords: ['carrot', 'vegetable'] },
      { char: '🌽', name: 'ear of corn', keywords: ['corn'] },
      { char: '🌶️', name: 'hot pepper', keywords: ['pepper', 'spicy', 'chili'] },
      { char: '🥔', name: 'potato', keywords: ['potato'] },
      { char: '🍔', name: 'hamburger', keywords: ['burger', 'food'] },
      { char: '🍟', name: 'french fries', keywords: ['fries', 'food'] },
      { char: '🍕', name: 'pizza', keywords: ['pizza', 'food'] },
      { char: '🌭', name: 'hot dog', keywords: ['hotdog', 'food'] },
      { char: '🥪', name: 'sandwich', keywords: ['sandwich', 'food'] },
      { char: '🌮', name: 'taco', keywords: ['taco', 'food', 'mexican'] },
      { char: '🌯', name: 'burrito', keywords: ['burrito', 'food'] },
      { char: '🥙', name: 'stuffed flatbread', keywords: ['kebab', 'food'] },
      { char: '🍳', name: 'cooking', keywords: ['egg', 'breakfast', 'fry'] },
      { char: '🥚', name: 'egg', keywords: ['egg'] },
      { char: '🧀', name: 'cheese wedge', keywords: ['cheese'] },
      { char: '🥓', name: 'bacon', keywords: ['bacon', 'breakfast'] },
      { char: '🥞', name: 'pancakes', keywords: ['pancake', 'breakfast'] },
      { char: '🧇', name: 'waffle', keywords: ['waffle', 'breakfast'] },
      { char: '🍞', name: 'bread', keywords: ['bread'] },
      { char: '🥐', name: 'croissant', keywords: ['croissant', 'bread'] },
      { char: '🥨', name: 'pretzel', keywords: ['pretzel'] },
      { char: '🍗', name: 'poultry leg', keywords: ['chicken', 'meat'] },
      { char: '🍖', name: 'meat on bone', keywords: ['meat'] },
      { char: '🥩', name: 'cut of meat', keywords: ['steak', 'meat'] },
      { char: '🍝', name: 'spaghetti', keywords: ['pasta', 'noodles'] },
      { char: '🍜', name: 'steaming bowl', keywords: ['ramen', 'noodles', 'soup'] },
      { char: '🍲', name: 'pot of food', keywords: ['stew', 'soup'] },
      { char: '🍛', name: 'curry rice', keywords: ['curry', 'rice'] },
      { char: '🍣', name: 'sushi', keywords: ['sushi', 'fish'] },
      { char: '🍱', name: 'bento box', keywords: ['bento', 'lunch'] },
      { char: '🍚', name: 'cooked rice', keywords: ['rice'] },
      { char: '🍙', name: 'rice ball', keywords: ['onigiri', 'rice'] },
      { char: '🥟', name: 'dumpling', keywords: ['dumpling', 'food'] },
      { char: '🍦', name: 'soft ice cream', keywords: ['ice cream', 'dessert'] },
      { char: '🍰', name: 'shortcake', keywords: ['cake', 'dessert'] },
      { char: '🎂', name: 'birthday cake', keywords: ['cake', 'birthday'] },
      { char: '🧁', name: 'cupcake', keywords: ['cupcake', 'dessert'] },
      { char: '🍪', name: 'cookie', keywords: ['cookie', 'dessert'] },
      { char: '🍩', name: 'doughnut', keywords: ['donut', 'dessert'] },
      { char: '🍫', name: 'chocolate bar', keywords: ['chocolate', 'candy'] },
      { char: '🍬', name: 'candy', keywords: ['candy', 'sweet'] },
      { char: '🍭', name: 'lollipop', keywords: ['lollipop', 'candy'] },
      { char: '🍯', name: 'honey pot', keywords: ['honey'] },
      { char: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'drink'] },
      { char: '🍵', name: 'teacup', keywords: ['tea', 'drink'] },
      { char: '🧃', name: 'beverage box', keywords: ['juice', 'drink'] },
      { char: '🥤', name: 'cup with straw', keywords: ['soda', 'drink'] },
      { char: '🍺', name: 'beer mug', keywords: ['beer', 'drink'] },
      { char: '🍻', name: 'clinking beer mugs', keywords: ['beer', 'cheers'] },
      { char: '🍷', name: 'wine glass', keywords: ['wine', 'drink'] },
      { char: '🍸', name: 'cocktail glass', keywords: ['cocktail', 'martini'] },
      { char: '🍹', name: 'tropical drink', keywords: ['cocktail', 'drink'] },
      { char: '🥂', name: 'clinking glasses', keywords: ['cheers', 'celebrate'] },
      { char: '🍾', name: 'bottle with popping cork', keywords: ['champagne', 'celebrate'] },
    ],
  },
  {
    id: 'activities',
    name: 'Activities',
    icon: 'fa-futbol',
    emojis: [
      { char: '⚽', name: 'soccer ball', keywords: ['soccer', 'football', 'sport'] },
      { char: '🏀', name: 'basketball', keywords: ['basketball', 'sport'] },
      { char: '🏈', name: 'american football', keywords: ['football', 'sport'] },
      { char: '⚾', name: 'baseball', keywords: ['baseball', 'sport'] },
      { char: '🥎', name: 'softball', keywords: ['softball', 'sport'] },
      { char: '🎾', name: 'tennis', keywords: ['tennis', 'sport'] },
      { char: '🏐', name: 'volleyball', keywords: ['volleyball', 'sport'] },
      { char: '🏉', name: 'rugby football', keywords: ['rugby', 'sport'] },
      { char: '🎱', name: 'pool 8 ball', keywords: ['pool', 'billiards'] },
      { char: '🏓', name: 'ping pong', keywords: ['table tennis', 'sport'] },
      { char: '🏸', name: 'badminton', keywords: ['badminton', 'sport'] },
      { char: '🥅', name: 'goal net', keywords: ['goal', 'sport'] },
      { char: '🏒', name: 'ice hockey', keywords: ['hockey', 'sport'] },
      { char: '🏑', name: 'field hockey', keywords: ['hockey', 'sport'] },
      { char: '🏏', name: 'cricket game', keywords: ['cricket', 'sport'] },
      { char: '⛳', name: 'flag in hole', keywords: ['golf', 'sport'] },
      { char: '🏹', name: 'bow and arrow', keywords: ['archery', 'arrow'] },
      { char: '🎣', name: 'fishing pole', keywords: ['fishing'] },
      { char: '🥊', name: 'boxing glove', keywords: ['boxing', 'sport'] },
      { char: '🥋', name: 'martial arts uniform', keywords: ['karate', 'judo'] },
      { char: '⛸️', name: 'ice skate', keywords: ['skating', 'ice'] },
      { char: '🎿', name: 'skis', keywords: ['ski', 'snow'] },
      { char: '🛷', name: 'sled', keywords: ['sled', 'snow'] },
      { char: '🏂', name: 'snowboarder', keywords: ['snowboard', 'snow'] },
      { char: '🏋️', name: 'person lifting weights', keywords: ['gym', 'lift', 'workout'] },
      { char: '🤸', name: 'person cartwheeling', keywords: ['gymnastics', 'cartwheel'] },
      { char: '⛹️', name: 'person bouncing ball', keywords: ['basketball', 'sport'] },
      { char: '🚴', name: 'person biking', keywords: ['bike', 'cycling'] },
      { char: '🏊', name: 'person swimming', keywords: ['swim', 'pool'] },
      { char: '🏆', name: 'trophy', keywords: ['trophy', 'win', 'award'] },
      { char: '🥇', name: 'first place medal', keywords: ['gold', 'medal', 'win'] },
      { char: '🥈', name: 'second place medal', keywords: ['silver', 'medal'] },
      { char: '🥉', name: 'third place medal', keywords: ['bronze', 'medal'] },
      { char: '🏅', name: 'sports medal', keywords: ['medal', 'award'] },
      { char: '🎖️', name: 'military medal', keywords: ['medal', 'honor'] },
      { char: '🎗️', name: 'reminder ribbon', keywords: ['ribbon', 'awareness'] },
      { char: '🎫', name: 'ticket', keywords: ['ticket', 'event'] },
      { char: '🎟️', name: 'admission tickets', keywords: ['ticket', 'event'] },
      { char: '🎪', name: 'circus tent', keywords: ['circus', 'carnival'] },
      { char: '🎭', name: 'performing arts', keywords: ['theater', 'drama', 'masks'] },
      { char: '🎨', name: 'artist palette', keywords: ['art', 'paint'] },
      { char: '🎬', name: 'clapper board', keywords: ['movie', 'film', 'action'] },
      { char: '🎤', name: 'microphone', keywords: ['mic', 'sing', 'karaoke'] },
      { char: '🎧', name: 'headphone', keywords: ['music', 'headphones'] },
      { char: '🎼', name: 'musical score', keywords: ['music', 'notes'] },
      { char: '🎵', name: 'musical note', keywords: ['music', 'note'] },
      { char: '🎶', name: 'musical notes', keywords: ['music', 'notes'] },
      { char: '🎹', name: 'musical keyboard', keywords: ['piano', 'music'] },
      { char: '🥁', name: 'drum', keywords: ['drum', 'music'] },
      { char: '🎸', name: 'guitar', keywords: ['guitar', 'music'] },
      { char: '🎺', name: 'trumpet', keywords: ['trumpet', 'music'] },
      { char: '🎻', name: 'violin', keywords: ['violin', 'music'] },
      { char: '🎲', name: 'game die', keywords: ['dice', 'game', 'random'] },
      { char: '🎯', name: 'direct hit', keywords: ['target', 'dart', 'bullseye'] },
      { char: '🎮', name: 'video game', keywords: ['game', 'controller', 'gaming'] },
      { char: '🕹️', name: 'joystick', keywords: ['game', 'arcade'] },
      { char: '🎰', name: 'slot machine', keywords: ['slots', 'gamble', 'casino'] },
      { char: '🧩', name: 'puzzle piece', keywords: ['puzzle', 'jigsaw'] },
      { char: '🎉', name: 'party popper', keywords: ['party', 'celebrate', 'congrats'] },
      { char: '🎊', name: 'confetti ball', keywords: ['party', 'celebrate'] },
      { char: '🎈', name: 'balloon', keywords: ['balloon', 'party'] },
      { char: '🎁', name: 'wrapped gift', keywords: ['gift', 'present', 'birthday'] },
    ],
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    icon: 'fa-car',
    emojis: [
      { char: '🚗', name: 'automobile', keywords: ['car', 'drive'] },
      { char: '🚕', name: 'taxi', keywords: ['taxi', 'cab'] },
      { char: '🚙', name: 'sport utility vehicle', keywords: ['suv', 'car'] },
      { char: '🚌', name: 'bus', keywords: ['bus'] },
      { char: '🚎', name: 'trolleybus', keywords: ['bus', 'trolley'] },
      { char: '🏎️', name: 'racing car', keywords: ['race', 'car', 'fast'] },
      { char: '🚓', name: 'police car', keywords: ['police', 'cop'] },
      { char: '🚑', name: 'ambulance', keywords: ['ambulance', 'medical'] },
      { char: '🚒', name: 'fire engine', keywords: ['fire truck'] },
      { char: '🚐', name: 'minibus', keywords: ['van', 'bus'] },
      { char: '🚚', name: 'delivery truck', keywords: ['truck', 'delivery'] },
      { char: '🚛', name: 'articulated lorry', keywords: ['truck', 'lorry'] },
      { char: '🚜', name: 'tractor', keywords: ['tractor', 'farm'] },
      { char: '🏍️', name: 'motorcycle', keywords: ['motorcycle', 'bike'] },
      { char: '🛵', name: 'motor scooter', keywords: ['scooter'] },
      { char: '🚲', name: 'bicycle', keywords: ['bike', 'bicycle'] },
      { char: '🛴', name: 'kick scooter', keywords: ['scooter'] },
      { char: '🚂', name: 'locomotive', keywords: ['train'] },
      { char: '🚆', name: 'train', keywords: ['train'] },
      { char: '🚇', name: 'metro', keywords: ['subway', 'metro'] },
      { char: '🚊', name: 'tram', keywords: ['tram'] },
      { char: '🚉', name: 'station', keywords: ['train', 'station'] },
      { char: '✈️', name: 'airplane', keywords: ['plane', 'flight', 'travel'] },
      { char: '🛫', name: 'airplane departure', keywords: ['takeoff', 'flight'] },
      { char: '🛬', name: 'airplane arrival', keywords: ['landing', 'flight'] },
      { char: '🚁', name: 'helicopter', keywords: ['helicopter'] },
      { char: '🚀', name: 'rocket', keywords: ['rocket', 'launch', 'space'] },
      { char: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien'] },
      { char: '⛵', name: 'sailboat', keywords: ['boat', 'sail'] },
      { char: '🚤', name: 'speedboat', keywords: ['boat', 'speed'] },
      { char: '🛥️', name: 'motor boat', keywords: ['boat'] },
      { char: '🚢', name: 'ship', keywords: ['ship', 'boat', 'cruise'] },
      { char: '⚓', name: 'anchor', keywords: ['anchor', 'ship'] },
      { char: '🚧', name: 'construction', keywords: ['construction', 'barrier'] },
      { char: '🚦', name: 'vertical traffic light', keywords: ['traffic', 'light'] },
      { char: '🗺️', name: 'world map', keywords: ['map', 'travel'] },
      { char: '🗽', name: 'Statue of Liberty', keywords: ['liberty', 'new york'] },
      { char: '🗼', name: 'Tokyo Tower', keywords: ['tokyo', 'tower'] },
      { char: '🏰', name: 'castle', keywords: ['castle'] },
      { char: '🏯', name: 'Japanese castle', keywords: ['castle', 'japan'] },
      { char: '🏟️', name: 'stadium', keywords: ['stadium'] },
      { char: '🎡', name: 'ferris wheel', keywords: ['fair', 'carnival'] },
      { char: '🎢', name: 'roller coaster', keywords: ['coaster', 'theme park'] },
      { char: '🎠', name: 'carousel horse', keywords: ['carousel', 'merry-go-round'] },
      { char: '⛲', name: 'fountain', keywords: ['fountain'] },
      { char: '⛱️', name: 'umbrella on ground', keywords: ['beach', 'umbrella'] },
      { char: '🏖️', name: 'beach with umbrella', keywords: ['beach', 'vacation'] },
      { char: '🏝️', name: 'desert island', keywords: ['island', 'beach'] },
      { char: '🏔️', name: 'snow-capped mountain', keywords: ['mountain', 'snow'] },
      { char: '⛰️', name: 'mountain', keywords: ['mountain'] },
      { char: '🌋', name: 'volcano', keywords: ['volcano'] },
      { char: '🏕️', name: 'camping', keywords: ['camp', 'tent'] },
      { char: '🏠', name: 'house', keywords: ['house', 'home'] },
      { char: '🏡', name: 'house with garden', keywords: ['house', 'home'] },
      { char: '🏢', name: 'office building', keywords: ['office', 'building'] },
      { char: '🏬', name: 'department store', keywords: ['store', 'mall'] },
      { char: '🏨', name: 'hotel', keywords: ['hotel'] },
      { char: '🏥', name: 'hospital', keywords: ['hospital'] },
      { char: '🏦', name: 'bank', keywords: ['bank'] },
      { char: '🏫', name: 'school', keywords: ['school'] },
      { char: '⛪', name: 'church', keywords: ['church'] },
      { char: '🌃', name: 'night with stars', keywords: ['city', 'night'] },
      { char: '🌉', name: 'bridge at night', keywords: ['bridge', 'night'] },
      { char: '🌁', name: 'foggy', keywords: ['fog', 'city'] },
    ],
  },
  {
    id: 'objects',
    name: 'Objects',
    icon: 'fa-lightbulb',
    emojis: [
      { char: '⌚', name: 'watch', keywords: ['watch', 'time'] },
      { char: '📱', name: 'mobile phone', keywords: ['phone', 'mobile'] },
      { char: '💻', name: 'laptop', keywords: ['laptop', 'computer'] },
      { char: '⌨️', name: 'keyboard', keywords: ['keyboard', 'type'] },
      { char: '🖥️', name: 'desktop computer', keywords: ['computer', 'pc'] },
      { char: '🖨️', name: 'printer', keywords: ['printer'] },
      { char: '🖱️', name: 'computer mouse', keywords: ['mouse'] },
      { char: '💾', name: 'floppy disk', keywords: ['save', 'disk'] },
      { char: '💿', name: 'optical disk', keywords: ['cd', 'disk'] },
      { char: '📀', name: 'dvd', keywords: ['dvd', 'disk'] },
      { char: '📷', name: 'camera', keywords: ['camera', 'photo'] },
      { char: '📸', name: 'camera with flash', keywords: ['camera', 'photo'] },
      { char: '📹', name: 'video camera', keywords: ['video', 'camera'] },
      { char: '🎥', name: 'movie camera', keywords: ['movie', 'film'] },
      { char: '📞', name: 'telephone receiver', keywords: ['phone', 'call'] },
      { char: '📟', name: 'pager', keywords: ['pager'] },
      { char: '📺', name: 'television', keywords: ['tv', 'television'] },
      { char: '📻', name: 'radio', keywords: ['radio'] },
      { char: '🔋', name: 'battery', keywords: ['battery', 'charge'] },
      { char: '🔌', name: 'electric plug', keywords: ['plug', 'power'] },
      { char: '💡', name: 'light bulb', keywords: ['idea', 'light', 'bulb'] },
      { char: '🔦', name: 'flashlight', keywords: ['flashlight', 'torch'] },
      { char: '🕯️', name: 'candle', keywords: ['candle'] },
      { char: '💸', name: 'money with wings', keywords: ['money', 'spend'] },
      { char: '💵', name: 'dollar banknote', keywords: ['money', 'cash', 'dollar'] },
      { char: '💰', name: 'money bag', keywords: ['money', 'rich'] },
      { char: '💳', name: 'credit card', keywords: ['card', 'pay'] },
      { char: '💎', name: 'gem stone', keywords: ['diamond', 'gem', 'jewel'] },
      { char: '⚖️', name: 'balance scale', keywords: ['justice', 'law', 'balance'] },
      { char: '🔧', name: 'wrench', keywords: ['wrench', 'tool', 'fix'] },
      { char: '🔨', name: 'hammer', keywords: ['hammer', 'tool'] },
      { char: '🛠️', name: 'hammer and wrench', keywords: ['tools', 'fix'] },
      { char: '⚙️', name: 'gear', keywords: ['gear', 'settings'] },
      { char: '🔩', name: 'nut and bolt', keywords: ['bolt', 'hardware'] },
      { char: '🧰', name: 'toolbox', keywords: ['tools', 'toolbox'] },
      { char: '🧲', name: 'magnet', keywords: ['magnet'] },
      { char: '🔫', name: 'water pistol', keywords: ['gun', 'water'] },
      { char: '💣', name: 'bomb', keywords: ['bomb', 'explode'] },
      { char: '🔪', name: 'kitchen knife', keywords: ['knife', 'cut'] },
      { char: '🗡️', name: 'dagger', keywords: ['dagger', 'sword'] },
      { char: '🛡️', name: 'shield', keywords: ['shield', 'protect'] },
      { char: '🔬', name: 'microscope', keywords: ['science', 'microscope'] },
      { char: '🔭', name: 'telescope', keywords: ['telescope', 'space'] },
      { char: '💊', name: 'pill', keywords: ['pill', 'medicine'] },
      { char: '💉', name: 'syringe', keywords: ['needle', 'shot', 'vaccine'] },
      { char: '🩹', name: 'adhesive bandage', keywords: ['bandage', 'bandaid'] },
      { char: '🔑', name: 'key', keywords: ['key', 'lock'] },
      { char: '🔒', name: 'locked', keywords: ['lock', 'secure'] },
      { char: '🔓', name: 'unlocked', keywords: ['unlock', 'open'] },
      { char: '🔔', name: 'bell', keywords: ['bell', 'notification'] },
      { char: '🔕', name: 'bell with slash', keywords: ['mute', 'silent'] },
      { char: '📣', name: 'megaphone', keywords: ['announce', 'loud'] },
      { char: '📢', name: 'loudspeaker', keywords: ['announce', 'loud'] },
      { char: '📌', name: 'pushpin', keywords: ['pin', 'location'] },
      { char: '📎', name: 'paperclip', keywords: ['clip', 'attach'] },
      { char: '✂️', name: 'scissors', keywords: ['cut', 'scissors'] },
      { char: '🖊️', name: 'pen', keywords: ['pen', 'write'] },
      { char: '✏️', name: 'pencil', keywords: ['pencil', 'write', 'edit'] },
      { char: '📝', name: 'memo', keywords: ['note', 'write', 'memo'] },
      { char: '📖', name: 'open book', keywords: ['book', 'read'] },
      { char: '📚', name: 'books', keywords: ['books', 'study'] },
      { char: '📅', name: 'calendar', keywords: ['calendar', 'date'] },
      { char: '📈', name: 'chart increasing', keywords: ['chart', 'up', 'growth'] },
      { char: '📉', name: 'chart decreasing', keywords: ['chart', 'down', 'loss'] },
      { char: '📊', name: 'bar chart', keywords: ['chart', 'stats'] },
      { char: '📦', name: 'package', keywords: ['box', 'package', 'shipping'] },
      { char: '✉️', name: 'envelope', keywords: ['mail', 'email', 'letter'] },
      { char: '📧', name: 'e-mail', keywords: ['email', 'mail'] },
      { char: '🗑️', name: 'wastebasket', keywords: ['trash', 'delete', 'bin'] },
      { char: '🛒', name: 'shopping cart', keywords: ['cart', 'shop'] },
      { char: '🎓', name: 'graduation cap', keywords: ['graduate', 'school', 'degree'] },
      { char: '👑', name: 'crown', keywords: ['crown', 'king', 'queen', 'royal'] },
      { char: '💍', name: 'ring', keywords: ['ring', 'marriage', 'engagement'] },
      { char: '⏰', name: 'alarm clock', keywords: ['alarm', 'clock', 'time'] },
      { char: '⏳', name: 'hourglass not done', keywords: ['time', 'wait'] },
      { char: '🧪', name: 'test tube', keywords: ['science', 'chemistry'] },
    ],
  },
  {
    id: 'symbols',
    name: 'Symbols',
    icon: 'fa-heart',
    emojis: [
      { char: '❤️', name: 'red heart', keywords: ['love', 'heart'] },
      { char: '🧡', name: 'orange heart', keywords: ['heart', 'love'] },
      { char: '💛', name: 'yellow heart', keywords: ['heart', 'love'] },
      { char: '💚', name: 'green heart', keywords: ['heart', 'love'] },
      { char: '💙', name: 'blue heart', keywords: ['heart', 'love'] },
      { char: '💜', name: 'purple heart', keywords: ['heart', 'love'] },
      { char: '🖤', name: 'black heart', keywords: ['heart'] },
      { char: '🤍', name: 'white heart', keywords: ['heart'] },
      { char: '🤎', name: 'brown heart', keywords: ['heart'] },
      { char: '💔', name: 'broken heart', keywords: ['heartbreak', 'sad'] },
      { char: '❣️', name: 'heart exclamation', keywords: ['heart', 'love'] },
      { char: '💕', name: 'two hearts', keywords: ['love', 'hearts'] },
      { char: '💞', name: 'revolving hearts', keywords: ['love', 'hearts'] },
      { char: '💓', name: 'beating heart', keywords: ['love', 'heart'] },
      { char: '💗', name: 'growing heart', keywords: ['love', 'heart'] },
      { char: '💖', name: 'sparkling heart', keywords: ['love', 'heart', 'sparkle'] },
      { char: '💘', name: 'heart with arrow', keywords: ['love', 'cupid'] },
      { char: '💝', name: 'heart with ribbon', keywords: ['love', 'gift'] },
      { char: '💟', name: 'heart decoration', keywords: ['heart', 'love'] },
      { char: '☮️', name: 'peace symbol', keywords: ['peace'] },
      { char: '✝️', name: 'latin cross', keywords: ['cross', 'christian'] },
      { char: '☪️', name: 'star and crescent', keywords: ['islam', 'muslim'] },
      { char: '🕉️', name: 'om', keywords: ['hindu', 'om'] },
      { char: '✡️', name: 'star of David', keywords: ['jewish', 'star'] },
      { char: '☯️', name: 'yin yang', keywords: ['balance', 'tao'] },
      { char: '💫', name: 'dizzy', keywords: ['star', 'sparkle'] },
      { char: '💥', name: 'collision', keywords: ['boom', 'explode'] },
      { char: '💢', name: 'anger symbol', keywords: ['angry', 'mad'] },
      { char: '💦', name: 'sweat droplets', keywords: ['sweat', 'water'] },
      { char: '💨', name: 'dashing away', keywords: ['fast', 'wind', 'gone'] },
      { char: '✅', name: 'check mark button', keywords: ['check', 'done', 'yes'] },
      { char: '☑️', name: 'check box with check', keywords: ['check', 'done'] },
      { char: '✔️', name: 'check mark', keywords: ['check', 'done', 'yes'] },
      { char: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'x'] },
      { char: '❎', name: 'cross mark button', keywords: ['no', 'wrong'] },
      { char: '➕', name: 'plus', keywords: ['add', 'plus'] },
      { char: '➖', name: 'minus', keywords: ['minus', 'subtract'] },
      { char: '➗', name: 'divide', keywords: ['divide'] },
      { char: '✖️', name: 'multiply', keywords: ['multiply', 'times'] },
      { char: '❓', name: 'question mark', keywords: ['question', 'help'] },
      { char: '❗', name: 'exclamation mark', keywords: ['important', 'exclamation'] },
      { char: '💯', name: 'hundred points', keywords: ['100', 'perfect', 'score'] },
      { char: '🔆', name: 'bright button', keywords: ['bright', 'light'] },
      { char: '⚠️', name: 'warning', keywords: ['warning', 'caution'] },
      { char: '🚫', name: 'prohibited', keywords: ['no', 'forbidden', 'ban'] },
      { char: '♻️', name: 'recycling symbol', keywords: ['recycle', 'green'] },
      { char: '🔱', name: 'trident emblem', keywords: ['trident'] },
      { char: '⚜️', name: 'fleur-de-lis', keywords: ['fleur'] },
      { char: '🆗', name: 'OK button', keywords: ['ok', 'okay'] },
      { char: '🆕', name: 'NEW button', keywords: ['new'] },
      { char: '🆒', name: 'COOL button', keywords: ['cool'] },
      { char: '🆓', name: 'FREE button', keywords: ['free'] },
      { char: '🔝', name: 'TOP arrow', keywords: ['top', 'up'] },
      { char: '🔙', name: 'BACK arrow', keywords: ['back'] },
      { char: '➡️', name: 'right arrow', keywords: ['arrow', 'right'] },
      { char: '⬅️', name: 'left arrow', keywords: ['arrow', 'left'] },
      { char: '⬆️', name: 'up arrow', keywords: ['arrow', 'up'] },
      { char: '⬇️', name: 'down arrow', keywords: ['arrow', 'down'] },
      { char: '🔄', name: 'counterclockwise arrows', keywords: ['refresh', 'sync', 'reload'] },
      { char: '🔁', name: 'repeat', keywords: ['repeat', 'loop'] },
      { char: '▶️', name: 'play button', keywords: ['play'] },
      { char: '⏸️', name: 'pause button', keywords: ['pause'] },
      { char: '⏹️', name: 'stop button', keywords: ['stop'] },
      { char: '🔀', name: 'shuffle', keywords: ['shuffle', 'random'] },
      { char: '#️⃣', name: 'keycap number sign', keywords: ['hash', 'pound'] },
      { char: '💲', name: 'heavy dollar sign', keywords: ['dollar', 'money'] },
      { char: '©️', name: 'copyright', keywords: ['copyright'] },
      { char: '®️', name: 'registered', keywords: ['registered'] },
      { char: '™️', name: 'trade mark', keywords: ['trademark'] },
    ],
  },
  {
    id: 'flags',
    name: 'Flags',
    icon: 'fa-flag',
    emojis: [
      { char: '🏁', name: 'chequered flag', keywords: ['race', 'finish', 'flag'] },
      { char: '🚩', name: 'triangular flag', keywords: ['flag', 'marker'] },
      { char: '🎌', name: 'crossed flags', keywords: ['flags', 'japan'] },
      { char: '🏴', name: 'black flag', keywords: ['flag', 'black'] },
      { char: '🏳️', name: 'white flag', keywords: ['flag', 'surrender'] },
      { char: '🏳️‍🌈', name: 'rainbow flag', keywords: ['pride', 'lgbt', 'rainbow'] },
      { char: '🏴‍☠️', name: 'pirate flag', keywords: ['pirate', 'skull'] },
      { char: '🇺🇸', name: 'flag United States', keywords: ['usa', 'america', 'flag'] },
      { char: '🇬🇧', name: 'flag United Kingdom', keywords: ['uk', 'britain', 'flag'] },
      { char: '🇨🇦', name: 'flag Canada', keywords: ['canada', 'flag'] },
      { char: '🇦🇺', name: 'flag Australia', keywords: ['australia', 'flag'] },
      { char: '🇩🇪', name: 'flag Germany', keywords: ['germany', 'flag'] },
      { char: '🇫🇷', name: 'flag France', keywords: ['france', 'flag'] },
      { char: '🇪🇸', name: 'flag Spain', keywords: ['spain', 'flag'] },
      { char: '🇮🇹', name: 'flag Italy', keywords: ['italy', 'flag'] },
      { char: '🇯🇵', name: 'flag Japan', keywords: ['japan', 'flag'] },
      { char: '🇰🇷', name: 'flag South Korea', keywords: ['korea', 'flag'] },
      { char: '🇨🇳', name: 'flag China', keywords: ['china', 'flag'] },
      { char: '🇮🇳', name: 'flag India', keywords: ['india', 'flag'] },
      { char: '🇧🇷', name: 'flag Brazil', keywords: ['brazil', 'flag'] },
      { char: '🇲🇽', name: 'flag Mexico', keywords: ['mexico', 'flag'] },
      { char: '🇷🇺', name: 'flag Russia', keywords: ['russia', 'flag'] },
      { char: '🇳🇱', name: 'flag Netherlands', keywords: ['netherlands', 'flag'] },
      { char: '🇸🇪', name: 'flag Sweden', keywords: ['sweden', 'flag'] },
      { char: '🇳🇴', name: 'flag Norway', keywords: ['norway', 'flag'] },
      { char: '🇵🇹', name: 'flag Portugal', keywords: ['portugal', 'flag'] },
      { char: '🇮🇪', name: 'flag Ireland', keywords: ['ireland', 'flag'] },
      { char: '🇵🇱', name: 'flag Poland', keywords: ['poland', 'flag'] },
      { char: '🇬🇷', name: 'flag Greece', keywords: ['greece', 'flag'] },
      { char: '🇹🇷', name: 'flag Turkey', keywords: ['turkey', 'flag'] },
      { char: '🇸🇦', name: 'flag Saudi Arabia', keywords: ['saudi', 'arabia', 'flag'] },
      { char: '🇿🇦', name: 'flag South Africa', keywords: ['south africa', 'flag'] },
      { char: '🇦🇪', name: 'flag United Arab Emirates', keywords: ['uae', 'emirates', 'flag'] },
      { char: '🇪🇬', name: 'flag Egypt', keywords: ['egypt', 'flag'] },
      { char: '🇦🇷', name: 'flag Argentina', keywords: ['argentina', 'flag'] },
    ],
  },
];

/**
 * Flat case-insensitive search over emoji name + keywords. Returns up to `limit` matches across all
 * categories. An empty/blank query returns [] (the picker shows categories instead in that case).
 */
export function searchEmojis(query: string, limit = 60): EmojiItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const results: EmojiItem[] = [];
  for (const category of EMOJI_CATEGORIES) {
    for (const emoji of category.emojis) {
      if (emoji.name.includes(q) || emoji.keywords.some((k) => k.includes(q))) {
        results.push(emoji);
        if (results.length >= limit) return results;
      }
    }
  }
  return results;
}
